"use strict";
window.dict = {
    "zh-CN": {
        NAV_HOME                             : "主頁",
        NAV_02                               : "項目定位",
        NAV_03                               : "項目思路",
        NAV_04                               : "應用場景",
        NAV_05                               : "團隊介紹",
        NAV_06                               : "Token",
        NAV_07                               : "區塊瀏覽器",
        CURRENT_LANGUAGE                     : "中文",
        CURRENT_LANGUAGE_EN                  : "英文",
        LOGIN                                : "登錄",
        REGISTER                             : "註冊",
        ACCOUNT                              : "用戶中心",
        WHITEPAPER                           : "白皮書",
        SECTION_HOME_TITLE                   : "以太秀秀",
        SECTION_HOME_SUBTITLE                : "",
        SECTION_HOME_DESC                    : "我的作品我作主",
        SECTION_HOME_DESC2                   : "--个人专利的追溯体系",
        SECTION_HOME_DOWNLOAD_WHITEPAPER     : "下載白皮書",
        SECTION_HOME_DOWNLOAD_WHITEPAPER_HREF: "./src/white-book.pdf",
        SECTION_HOME_DOWNLOAD_WHITEPAPER_HREF_EN:"./src/white-book-en.pdf",
        SECTION_PROBLEM_TITLE                : "市場痛點",
        SECTION_PROBLEM_SUB_TITLE            : "確權、舉證、維權成本",
        SECTION_PROBLEM_DESC                 : "",
        SECTION_PROBLEM_LIST_ITEM_1          : "確權難。大部分創作者雖然深知盜版抄襲威脅，但傳統版權登記方式不僅耗時長而且費用高，對於互聯網創作者來說實在不是一種划算的保護方式，因而大多數網路創作者不登記、不保護，導致侵權頻發、版權時刻處於危險之中；",
        SECTION_PROBLEM_LIST_ITEM_2          : "舉證難。最氣人的是，抄襲者往往理直氣壯，要麼不理不管，要麼死不認證，碰到更無恥還要求你拿出證據，而被法律認可的證據往往是維權的關鍵；",
        SECTION_PROBLEM_LIST_ITEM_3          : "維權成本高。平臺投訴手續的複雜，法律訴訟成本更高……大多數原創者因此選擇保持沉默，任由權利被侵犯",
        SECTION_SOLUTION_TITLE               : "我們的解決方案",
        SECTION_SOLUTION_SUB_TITLE           : "",
        SECTION_SOLUTION_LIST_TIT_1          : "區塊鏈時間戳",
        SECTION_SOLUTION_LIST_ITEM_1         : "利用區塊鏈時間戳記建立“數位身份證”，從源頭保護原創版權，滿足後續維權和版權變現等需求。",
        SECTION_SOLUTION_LIST_TIT_2          : "區塊鏈溯源",
        SECTION_SOLUTION_LIST_ITEM_2         : "利用區塊鏈可追蹤性、公開、透明的特點，實現網路傳播的源頭追溯，舉證輕鬆解決。",
        SECTION_SOLUTION_LIST_TIT_3          : "低成本維權",
        SECTION_SOLUTION_LIST_ITEM_3         : "區塊鏈平臺幾乎零成本，完全免去了以往令維權者頭痛的各種維權成本。",
        SECTION_INFLUENCER_TITLE             : "發起人",
        SECTION_INFLUENCER_ITEM_1            : "Channing 商業架構設計",
        SECTION_INFLUENCER_ITEM_2            : "Ben 技術團隊負責人",
        SECTION_INFLUENCER_ITEM_3            : "Alger 區塊鏈總架構師",
        SECTION_INFLUENCER_ITEM_4            : "電影明星",
        SECTION_INFLUENCER_ITEM_5            : "博主",
        SECTION_INFLUENCER_ITEM_6            : "意見領袖",
        SECTION_INEX_TITLE                   : "影力所(INEX)",
        SECTION_INEX_SUB_TITLE               : "影力所(INEX)是整個區塊鏈應用在I以太秀秀體系中的核心價值。通過該平台，潛在的影響力可以通過使用創建基於個體的Token來流通和變現。",
        SECTION_BUYCLUB_TITLE                : "基於代幣的應用- ETHER SHOW",
        SECTION_BUYCLUB_SUB_TITLE            : "Ether show 是針對知識產權保護而推出的區塊鏈系統，基於區塊鏈以太坊技術，結合時間戳、區塊鏈溯源及專利保護於一體的價值互聯網體系。",
        SECTION_INNOVATION_TITLE             : "項目團隊",
        SECTION_INNOVATION_SUB_TITLE_1       : "對於公眾人物",
        SECTION_INNOVATION_SUB_TITLE_2       : "對於支持者/粉絲",
        SECTION_INNOVATION_ITEM_1            : "以太秀秀為公眾人物提供了一種創新型途徑，通過科學地分解動態變化，來量化其影響力。",
        SECTION_INNOVATION_ITEM_2            : "以太秀秀為公眾人物提供了一種創新方式來獲得粉絲的支持，並與他們的粉絲互動。",
        SECTION_INNOVATION_ITEM_3            : "對於公眾人物和他的粉絲來說，可以通過雙向流動的方式，在代幣交易中獲得價值，而非之前粉絲僅僅單向投入，而沒有任何可量化的回報。",
        SECTION_INNOVATION_ITEM_4            : "通過在影力所的定價，以及為代幣用途所開發的各種應用；支持者/粉絲和公眾人物之間日常互動將更加親密。",
        SECTION_TEAM_TITLE                   : "團隊",
        SECTION_TEAM_MEMBER_NAME_01          : "Rain Huan",
        SECTION_TEAM_MEMBER_TITLE_01         : "以太秀秀創始人",
        SECTION_TEAM_MEMBER_NAME_02          : "Yao Ge",
        SECTION_TEAM_MEMBER_TITLE_02         : "以太秀秀聯合創始人|合作運營",
        SECTION_TEAM_MEMBER_NAME_03          : "Heng Xia",
        SECTION_TEAM_MEMBER_TITLE_03         : "以太秀秀聯合創始人 |亞太運營中心合伙人",
        SECTION_TEAM_MEMBER_NAME_04          : "Freed Ma",
        SECTION_TEAM_MEMBER_TITLE_04         : "亞太運營中心首席運營官、合伙人",
        SECTION_TEAM_MEMBER_NAME_05          : "Jimmy Li",
        SECTION_TEAM_MEMBER_TITLE_05         : "亞太運營中心首席執行官、合伙人",
        SECTION_TEAM_MEMBER_NAME_06          : "Xinyao Xie",
        SECTION_TEAM_MEMBER_TITLE_06         : "以太秀秀聯合創始人| Sports Influence主管",
        SECTION_TEAM_MEMBER_NAME_07          : "Shayda Osman Jalal",
        SECTION_TEAM_MEMBER_TITLE_07         : "歐洲和中東運營中心合作人",
        SECTION_TEAM_MEMBER_NAME_08          : "Park Cheol Min",
        SECTION_TEAM_MEMBER_TITLE_08         : "韓國運營團隊合伙人",
        SECTION_TEAM_MEMBER_NAME_09          : "Kim Si Eun",
        SECTION_TEAM_MEMBER_TITLE_09         : "韓國運營團隊合伙人",
        SECTION_TEAM_MEMBER_NAME_10          : "James Wong",
        SECTION_TEAM_MEMBER_TITLE_10         : "以太秀秀聯合創始人| 全球業務開發",
        SECTION_TEAM_MEMBER_NAME_11          : "Jackie Ma",
        SECTION_TEAM_MEMBER_TITLE_11         : "業務開發總監",
        SECTION_TEAM_MEMBER_NAME_12          : "Sophia Li",
        SECTION_TEAM_MEMBER_TITLE_12         : "市場總監",
        SECTION_TEAM_MEMBER_NAME_13          : "Jesse Liu",
        SECTION_TEAM_MEMBER_TITLE_13         : "公眾人物運營總監",
        SECTION_TEAM_MEMBER_NAME_14          : "Luyao Zhang",
        SECTION_TEAM_MEMBER_TITLE_14         : "產品總監",
        SECTION_TEAM_MEMBER_NAME_15          : "Gang Lv",
        SECTION_TEAM_MEMBER_TITLE_15         : "以太秀秀技術總監",
        SECTION_TEAM_MEMBER_NAME_16          : "Xinyu Li",
        SECTION_TEAM_MEMBER_TITLE_16         : "社區運營總監",
        SECTION_PARTNER_TITLE                : "合作夥伴",
        SECTION_PARTNER_INTRO_1              : "Anomaly是一家於2004年在紐約成立的廣告代理商。該代理商在洛杉磯、紐約、多倫多、倫敦、阿姆斯特丹和上海均設有辦事處。",
        SECTION_PARTNER_INTRO_2              : "金科（代碼：837901）成立於2013年，是中國最年輕的新三板(NEEQ)上市公司。",
        SECTION_PARTNER_INTRO_3              : "全球區塊鏈研究中心，簡稱GBC，是一家專事區塊鏈研究的獨立機構，致力於區塊鏈行業的發展。",
        SECTION_PARTNER_INTRO_4              : "Alphacat 將是世界上第一個基於數字貨幣的量化投資平台，也是世界上第一個機器人交易機制，利用人工智能和大數據實施交易和投資管理。",
        SECTION_DOCUMENT_TITLE               : "白皮書",
        SECTION_DOCUMENT_DOWNLOAD            : "白皮書下載",
        SECTION_DOCUMENT_DOWNLOAD_HREF       : "./src/white-book.pdf",
        SECTION_INC_TOKEN_TITLE              : "以太秀秀",
        SECTION_INC_TOKEN_SUB_TITLE          : "代幣銷售計劃",
        SECTION_INC_TOKEN_STEP_1             : "天使輪",
        SECTION_INC_TOKEN_STEP_2             : "天使輪",
        SECTION_INC_TOKEN_STEP_3             : "天使輪",
        SECTION_INC_TOKEN_FINISHED           : "完成銷售",
        SECTION_ROADMAP_TITLE                : "推廣計劃",
        SECTION_ROADMAP_STEP_TITLE_1         : "深圳 01月20日",
        SECTION_ROADMAP_STEP_DESC_1          : "2018年首界中國區塊鏈應用峰會",
        SECTION_ROADMAP_STEP_TITLE_2         : "澳門 02月04日",
        SECTION_ROADMAP_STEP_DESC_2          : "2018年區塊鏈項目綜合路演推介儀式",
        SECTION_ROADMAP_STEP_TITLE_3         : "台灣 02月05日",
        SECTION_ROADMAP_STEP_DESC_3          : "待續",
        SECTION_ROADMAP_STEP_TITLE_4         : "待續",
        SECTION_NEWS_TITLE                   : "最新新聞",
        SECTION_NEWS_ITEM_TITLE_1            : "迪拜以太秀秀發佈會 & 影力所發佈會",
        SECTION_NEWS_ITEM_TITLE_2            : "鄧加和眾多足球巨星齊聚迪拜，為以太秀秀歐洲發佈會助力!",
        SECTION_NEWS_ITEM_TITLE_3            : "以太秀秀在曼谷與泰國王室聯合舉辦了一次發佈會",
        SECTION_NEWS_ITEM_TITLE_4            : "泰國王室成員、電影明星和來自世界各地的投資者都參加了在曼谷索菲特酒店舉辦的以太秀秀盛宴",
        SECTION_NEWS_ITEM_TITLE_5            : "韓國首爾以太秀秀發佈會",
        SECTION_FOLLOW_TITLE_1               : "免責聲明",
        SECTION_FOLLOW_TITLE_2               : "",
        FOOTER_POLICY                        : "© CopyRight 2017-2018",
        FOOTER_TERMS                         : "隱私政策",
        FOOTER_AGGREMENT                     : "條款",
        FOOTER_FUNDATION                     : "ESS.TW Inc. All Rights Reserved.",
        IMG_PROBLEM                          : "./src/problem-cn.png",
        IMG_SOLUTION                         : "./src/solution-cn.png",
        IMG_INC_TOKEN_1                      : "./src/inc-token-1-cn.png",
        IMG_INC_TOKEN_2                      : "./src/inc-token-2-cn.png",
        DIALOG_LOGIN_TITLE                   : "登錄",
        DIALOG_LOGIN_EMAIL                   : "郵箱",
        DIALOG_LOGIN_PASSWORD                : "密碼",
        DIALOG_LOGIN_IMAGE_CAPTCHA           : "圖形驗證碼",
        DIALOG_LOGIN_BTN_LOGIN               : "登錄",
        DIALOG_LOGIN_REMEMBER                : "記住我",
        DIALOG_LOGIN_FORGET                  : "忘記密碼？",
        DIALOG_REGISTER_TITLE                : "註冊",
        DIALOG_REGISTER_EMAIL                : "郵箱",
        DIALOG_REGISTER_PASSWORD             : "密碼",
        DIALOG_REGISTER_IMAGE_CAPTCHA        : "圖形驗證碼",
        DIALOG_REGISTER_EMAIL_CAPTCHA        : "郵箱驗證碼",
        DIALOG_REGISTER_BTN_REGISTER         : "註冊",
        DIALOG_REGISTER_CAN_NOT_REGISTER     : "無法註冊？",
        DIALOG_REGISTER_REGISTER_HELPER_1    : "將您的郵箱、姓名、身份證號、身份證照片發送到",
        DIALOG_REGISTER_REGISTER_HELPER_2    : "。我們將在 2 個工作日內完成驗證，並將您的登錄信息發送到您的郵箱",
        DIALOG_FORGET_TITLE                  : "重置密碼",
        DIALOG_FORGET_EMAIL                  : "郵箱",
        DIALOG_FORGET_IMAGE_CAPTCHA          : "圖形驗證碼",
        DIALOG_FORGET_EMAIL_CAPTCHA          : "郵箱驗證碼",
        DIALOG_FORGET_PASSWORD               : "密碼",
        DIALOG_FORGET_BTN_RESET              : "重置",
        DIALOG_FORGET_BACK_TO_LOGIN          : "返回登錄",
        DIALOG_AUTHENTICATION_TITLE          : "身份認證",
        DIALOG_AUTHENTICATION_SUB_TITLE      : "提交申購錢請先進行身份認證",
        DIALOG_AUTHENTICATION_REALNAME       : "真實姓名",
        DIALOG_AUTHENTICATION_ID_NUMBER      : "證件號",
        DIALOG_AUTHENTICATION_UPLOAD         : "請上傳證件照片",
        DIALOG_AUTHENTICATION_UPLOAD_HINT    : "請上傳您的身份證或者護照的圖片",
        DIALOG_AUTHENTICATION_IMAGE_CAPTCHA  : "圖形驗證碼",
        DIALOG_AUTHENTICATION_BTN_DONW       : "完成",
        GET_CODE                             : "獲取驗證碼",
        BTN_PRESALE                          : "預售",
        BTN_ACCOUNT                          : "賬戶",
        SELECT_NATIONALITY_DEFAULT           : "- 選擇國家 -",
        ERROR_INVALID_EMAIL                  : "請正確填寫的郵箱地址",
        ERROR_INVALID_PASSWORD               : "請正確填寫密碼",
        ERROR_INVALID_CAPTCHA                : "請正確填寫驗證碼",
        ERROR_INVALID_IMAGE_CAPTCHA          : "請正確填寫圖形驗證碼",
        ERROR_INVALID_EMAIL_CAPTCHA          : "請正確填寫郵箱驗證碼",
        ERROR_EMPTY_REALNAME                 : "請輸入真實姓名",
        ERROR_EMPTY_ID_NUMBER                : "請輸入證件號",
        ERROR_EMPTY_COUNTRY                  : "請輸入國家",
        ERROR_EMPTY_ID_PHOTO                 : "請上傳證件照片",
        MESSAGE_EMAIL_SENT                   : "郵件已發送",
        MESSAGE_PASSWORD_RESET               : "密碼已重置，現在帶您去登錄",
        DICT_XMZC:"項目主創",
        DICT_CYJJ:"產業聚焦",
        DICT_CYJJ_DL_1:"眾所周知，這是一個知識變現的黃金時代。原創者們最希望看見的，是自己的作品紅了；而最可悲的是，自己的作品讓別人紅了……抄襲、盜圖、肆意轉載等行為，在這個人人會翻防火牆的時代，變得如此普通，如此肆無忌憚。",
        DICT_CYJJ_DL_2:"這種情況，不僅給這些原創者經濟造成損失，同時限制了原創的積極性，對整個知識文化領域的發展產生了極大的消極影響。",
        DICT_CYJJ_BTN:"市場痛點",
        DICT_YYCJ:"應用場景",
        DICT_YYCJ_DL_01:"ESS實現了各種知識財產權的收集、確權、加密、存證、防盜版、交換、分發、評價、排行、發行、交易、打賞、眾籌、眾包等。",
        DICT_YYCJ_BTN:"應用場景",
        DICT_XMJS:"項目介紹",
        DICT_XMJS_DL_01:"凌志平先生在項目發起前指出：「將區塊鏈技術應用於知識產權領域，尤其是針對保護原創的文字、聲音、圖片、影像、專利、郵件發送即信息傳遞等內容，將起到前所未有的積極作用。",
        DICT_XMJS_DL_02:"「依照此方針，區塊鏈「以太秀秀（英文名稱：Ether show，簡寫：ESS）「，是以區塊鏈技術為底層的全球化，開放式生態系統。平台開放原始生態碼，開發者能夠建立和發佈新的項目，增進區塊鏈技術在更多產業的應用。",
        DICT_XMJS_DL_03:"ESS是基於以太坊智慧合約基礎上的國際技術領先的區塊鏈項目，是一個智慧的原創溯源平台，ESS由基礎層、架構層、應用層三層組成。",
        DICT_XMJS_BTN1:"項目主創",
        DICT_XMJS_BTN2:"解決方案",
        DICT_SP:"視頻",
        DICT_SP_DES:"凌志平先生致詞",

        TEAM_01_TIT:"技術團隊",
        TEAM_01_01_NAME:"區塊鏈總架構師 Alger",
        TEAM_01_01_DEC:"多年區塊鏈技術開發和實踐經驗",
        TEAM_01_01_DEC_02:"熟悉多代虛擬貨幣",
        TEAM_01_01_DEC_03:"熟悉區塊鏈產品底層代碼技術",
        TEAM_01_02_NAME:"技術團隊負責人 Ben",
        TEAM_01_02_DEC:"資深PHP工程師",
        TEAM_01_02_DEC_02:"資深安全檢測工程師",
        TEAM_01_02_DEC_03:"熟悉區塊鏈底層應用技術",
        TEAM_01_02_DEC_04:"熟悉股票交易系統",
        TEAM_01_02_DEC_05:"熟悉金融領域電腦軟體規則",

        TEAM_01_03_NAME:"商業架構設計 Channing",
        TEAM_01_03_DEC:"商業架構師",
        TEAM_01_03_DEC_02:"金融律師",
        TEAM_01_03_DEC_03:"互聯網領域的頂層商業架構設計",
        TEAM_01_03_DEC_04:"金融法律服務",

        TEAM_02_TIT:"財務團隊",
        TEAM_02_NAME:"吳郁隆",
        TEAM_02_DEC:"首席運營長 臺北",
        TEAM_02_DEC_001:"普華永道資誠(PwC Taiwan)",
        TEAM_02_NAME_02:"",
        TEAM_02_DEC_02:"",

        TEAM_03_TIT:"法律團隊",
        TEAM_03_NAME:"法務團隊:林皓堂",
        TEAM_03_DEC:"登錄法院:臺灣臺北地方法院",
        TEAM_03_DEC_2:"登錄公會:",
        TEAM_03_DEC_3:"台北律師公會",
        TEAM_03_DEC_4:"高雄律師公會",
        TEAM_03_DEC_5:"桃園律師公會",
        TEAM_03_BTN:"法律文書",

        TEAM_04_TIT:"顧問團隊",
        TEAM_04_01_NAME:"苏国历",
        TEAM_04_01_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_02_NAME:"鲁长军",
        TEAM_04_02_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_03_NAME:"贺铿",
        TEAM_04_03_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_04_NAME:"孙祺扬",
        TEAM_04_04_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_05_NAME:"邱鸿彬",
        TEAM_04_05_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_06_NAME:"吴忌寒",
        TEAM_04_06_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",

        DBYT_TIT:"代币用途",
        DBYT_DL_TIT:"維護以太秀秀區塊鏈的運行",
        DBYT_DL_DEC:"去中心化的以太秀秀作為分布式的記帳系統，需要用區塊鏈的Token激勵記帳節點參與記帳，維護區塊鏈的正常運行。",
        DBYT_DL_TIT_02:"商業應用交易",
        DBYT_DL_DEC_02:"以太秀秀上各種商業應用的交易支付: 打賞、權利交易費、發行代理費、平臺使用費、眾籌眾包提成、交易手續費、提現手續費等。",
        DBYT_DL_TIT_03:"Token",
        DBYT_DL_DEC_03:"以太秀秀幣總量：999999999億枚，永不增發。",

        ESS_TITLE:"以太秀秀",
        ESS_TITLE_02:"天使輪參與者",
        ESS_LIST_TYPE:"天使輪",
        ESS_LIST_STATUS:"參與完成",
        ESS_LIST_NAME_01:"澳門貿易投資促進會執行副會長 曾厚沃",
        ESS_LIST_NAME_02:"澳門天盈國際投資公司董事長 林遠迎",
        ESS_LIST_NAME_03:"澳門金馬國際投資董事兼總經理 張靖海",
        ESS_LIST_NAME_04:"澳門利發化工發展公司總經理 林溢常",

        STATEMENT:"該网站只用于傳達資訊之途，並不構成本專案買賣的相關意見。以上資訊或分析不構成投資決策。本网站不構成任何投資建議，投資意向或教唆投資。本文檔不組成也不理解為提供任何買賣證券的行為，也不是任何形式上的合約或者承諾。相關意向用戶明確瞭解本項目的風險，投資者一旦參與投資即表示瞭解並接受該項目風險，並願意個人為此承擔一切相應結果或後果。運營團隊不承擔任何參與本專案造成的直接或間接的損失。"
    },
    "en-US": {
        NAV_HOME                             : "Home",
        NAV_02                               : "Project location",
        NAV_03                               : "Project idea",
        NAV_04                               : "Application scene",
        NAV_05                               : "Team Introduction",
        NAV_06                               : "Token",
        NAV_07                               : "Block browsers",
        CURRENT_LANGUAGE                     : "Chinese",
        CURRENT_LANGUAGE_EN                  : "English",
        LOGIN                                : "登錄",
        REGISTER                             : "註冊",
        ACCOUNT                              : "User center",
        WHITEPAPER                           : "白皮書",
        SECTION_HOME_TITLE                   : "Ether show",
        SECTION_HOME_SUBTITLE                : "",
        SECTION_HOME_DESC                    : "I am the master of my work",
        SECTION_HOME_DESC2                   : "--The traceability system of individual patents",
        SECTION_HOME_DOWNLOAD_WHITEPAPER     : "white paper cn",
        SECTION_HOME_DOWNLOAD_WHITEPAPER_HREF: "./src/white-book.pdf",
        SECTION_HOME_DOWNLOAD_WHITEPAPER_HREF_EN:"./src/white-book-en.pdf",
        SECTION_PROBLEM_TITLE                : "Market pain point",
        SECTION_PROBLEM_SUB_TITLE            : "Confirmation, proof, cost of safeguarding rights.",
        SECTION_PROBLEM_DESC                 : "",
        SECTION_PROBLEM_LIST_ITEM_1          : "Counterpoising truly difficult. Although most creators know pirated copying threat, but traditional copyright registration method is not only time-consuming and high cost, for Internet creator is not a cost-effective way of protection, thus most creators network registration, protection, leading to frequent infringement, copyright moment in danger;",
        SECTION_PROBLEM_LIST_ITEM_2          : "The proof is difficult. Most irritating, a copycat is often justified, or ignore whether, or not certification, encounter more shameless also require you to take out the evidence, the evidence is recognised by the law can be key to rights;",
        SECTION_PROBLEM_LIST_ITEM_3          : "The cost of safeguarding rights is high. The complexity of the platform complaint procedure and the higher cost of legal action... Most original creators chose to remain silent and allow their rights to be violated.",
        SECTION_SOLUTION_TITLE               : "Our solution",
        SECTION_SOLUTION_SUB_TITLE           : "",
        SECTION_SOLUTION_LIST_TIT_1          : "Block chain timestamp",
        SECTION_SOLUTION_LIST_ITEM_1         : 'Use block chain time stamp to establish "digital identity card", protect original copyright from the source and meet the demand of subsequent rights protection and realization of copyright.',
        SECTION_SOLUTION_LIST_TIT_2          : "Block chain traceability",
        SECTION_SOLUTION_LIST_ITEM_2         : "By using the characteristics of blockchain traceability, openness and transparency, the source of network communication can be traced back and the proof can be easily solved.",
        SECTION_SOLUTION_LIST_TIT_3          : "Low cost protection",
        SECTION_SOLUTION_LIST_ITEM_3         : "The cost of the block chain platform is almost zero, eliminating all the costs of safeguarding the rights of activists in the past.",
        SECTION_INFLUENCER_TITLE             : "發起人",
        SECTION_INFLUENCER_ITEM_1            : "Channing 商業架構設計",
        SECTION_INFLUENCER_ITEM_2            : "Ben 技術團隊負責人",
        SECTION_INFLUENCER_ITEM_3            : "Alger 區塊鏈總架構師",
        SECTION_INFLUENCER_ITEM_4            : "電影明星",
        SECTION_INFLUENCER_ITEM_5            : "博主",
        SECTION_INFLUENCER_ITEM_6            : "意見領袖",
        SECTION_INEX_TITLE                   : "影力所(INEX)",
        SECTION_INEX_SUB_TITLE               : "影力所(INEX)是整個區塊鏈應用在I以太秀秀體系中的核心價值。通過該平台，潛在的影響力可以通過使用創建基於個體的Token來流通和變現。",
        SECTION_BUYCLUB_TITLE                : "The application of tokens-ETHER SHOW",
        SECTION_BUYCLUB_SUB_TITLE            : "Ether show is a block chain system for intellectual property protection, based on the block chain Ethernet technology, combining with timestamp, block chain traceability and patent protection of the value Internet system.",
        SECTION_INNOVATION_TITLE             : "Project team",
        SECTION_INNOVATION_SUB_TITLE_1       : "對於公眾人物",
        SECTION_INNOVATION_SUB_TITLE_2       : "對於支持者/粉絲",
        SECTION_INNOVATION_ITEM_1            : "以太秀秀為公眾人物提供了一種創新型途徑，通過科學地分解動態變化，來量化其影響力。",
        SECTION_INNOVATION_ITEM_2            : "以太秀秀為公眾人物提供了一種創新方式來獲得粉絲的支持，並與他們的粉絲互動。",
        SECTION_INNOVATION_ITEM_3            : "對於公眾人物和他的粉絲來說，可以通過雙向流動的方式，在代幣交易中獲得價值，而非之前粉絲僅僅單向投入，而沒有任何可量化的回報。",
        SECTION_INNOVATION_ITEM_4            : "通過在影力所的定價，以及為代幣用途所開發的各種應用；支持者/粉絲和公眾人物之間日常互動將更加親密。",
        SECTION_TEAM_TITLE                   : "團隊",
        SECTION_TEAM_MEMBER_NAME_01          : "Rain Huan",
        SECTION_TEAM_MEMBER_TITLE_01         : "以太秀秀創始人",
        SECTION_TEAM_MEMBER_NAME_02          : "Yao Ge",
        SECTION_TEAM_MEMBER_TITLE_02         : "以太秀秀聯合創始人|合作運營",
        SECTION_TEAM_MEMBER_NAME_03          : "Heng Xia",
        SECTION_TEAM_MEMBER_TITLE_03         : "以太秀秀聯合創始人 |亞太運營中心合伙人",
        SECTION_TEAM_MEMBER_NAME_04          : "Freed Ma",
        SECTION_TEAM_MEMBER_TITLE_04         : "亞太運營中心首席運營官、合伙人",
        SECTION_TEAM_MEMBER_NAME_05          : "Jimmy Li",
        SECTION_TEAM_MEMBER_TITLE_05         : "亞太運營中心首席執行官、合伙人",
        SECTION_TEAM_MEMBER_NAME_06          : "Xinyao Xie",
        SECTION_TEAM_MEMBER_TITLE_06         : "以太秀秀聯合創始人| Sports Influence主管",
        SECTION_TEAM_MEMBER_NAME_07          : "Shayda Osman Jalal",
        SECTION_TEAM_MEMBER_TITLE_07         : "歐洲和中東運營中心合作人",
        SECTION_TEAM_MEMBER_NAME_08          : "Park Cheol Min",
        SECTION_TEAM_MEMBER_TITLE_08         : "韓國運營團隊合伙人",
        SECTION_TEAM_MEMBER_NAME_09          : "Kim Si Eun",
        SECTION_TEAM_MEMBER_TITLE_09         : "韓國運營團隊合伙人",
        SECTION_TEAM_MEMBER_NAME_10          : "James Wong",
        SECTION_TEAM_MEMBER_TITLE_10         : "以太秀秀聯合創始人| 全球業務開發",
        SECTION_TEAM_MEMBER_NAME_11          : "Jackie Ma",
        SECTION_TEAM_MEMBER_TITLE_11         : "業務開發總監",
        SECTION_TEAM_MEMBER_NAME_12          : "Sophia Li",
        SECTION_TEAM_MEMBER_TITLE_12         : "市場總監",
        SECTION_TEAM_MEMBER_NAME_13          : "Jesse Liu",
        SECTION_TEAM_MEMBER_TITLE_13         : "公眾人物運營總監",
        SECTION_TEAM_MEMBER_NAME_14          : "Luyao Zhang",
        SECTION_TEAM_MEMBER_TITLE_14         : "產品總監",
        SECTION_TEAM_MEMBER_NAME_15          : "Gang Lv",
        SECTION_TEAM_MEMBER_TITLE_15         : "以太秀秀技術總監",
        SECTION_TEAM_MEMBER_NAME_16          : "Xinyu Li",
        SECTION_TEAM_MEMBER_TITLE_16         : "社區運營總監",
        SECTION_PARTNER_TITLE                : "Cooperative partner",
        SECTION_PARTNER_INTRO_1              : "Anomaly is an advertising agency established in New York in 2004. The agency has offices in Los Angeles, New York, Toronto, London, Amsterdam and Shanghai. ",
        SECTION_PARTNER_INTRO_2              : "Founded in 2013, jinke (code: 837901) is the youngest NEEQ listed company in China.",
        SECTION_PARTNER_INTRO_3              : "Research Center, global blockchain referred to as GBC, is an independent organization that specializes in block chain research, is committed to the development of industry chain block.",
        SECTION_PARTNER_INTRO_4              : "Alphacat will be the world's first quantitative investment platform based on digital currency, and the first robot trading mechanism in the world, using artificial intelligence and big data to carry out transaction and investment management.",
        SECTION_DOCUMENT_TITLE               : "The white paper",
        SECTION_DOCUMENT_DOWNLOAD            : "White paper downloading",
        SECTION_DOCUMENT_DOWNLOAD_HREF       : "./src/white-book-en.pdf",
        SECTION_INC_TOKEN_TITLE              : "以太秀秀",
        SECTION_INC_TOKEN_SUB_TITLE          : "代幣銷售計劃",
        SECTION_INC_TOKEN_STEP_1             : "天使輪",
        SECTION_INC_TOKEN_STEP_2             : "天使輪",
        SECTION_INC_TOKEN_STEP_3             : "天使輪",
        SECTION_INC_TOKEN_FINISHED           : "完成銷售",

        SECTION_ROADMAP_TITLE                : "Promotion plan",
        SECTION_ROADMAP_STEP_TITLE_1         : "Shenzhen 20, 01",
        SECTION_ROADMAP_STEP_DESC_1          : "The first world block chain application summit in 2018",
        SECTION_ROADMAP_STEP_TITLE_2         : "Macao 04, 02",
        SECTION_ROADMAP_STEP_DESC_2          : "Comprehensive roadshow promotion ceremony of block chain project in 2018",
        SECTION_ROADMAP_STEP_TITLE_3         : "Taiwan 05, 02",
        SECTION_ROADMAP_STEP_DESC_3          : "To be continued",
        SECTION_ROADMAP_STEP_TITLE_4         : "To be continued",
        SECTION_NEWS_TITLE                   : "最新新聞",
        SECTION_NEWS_ITEM_TITLE_1            : "迪拜以太秀秀發佈會 & 影力所發佈會",
        SECTION_NEWS_ITEM_TITLE_2            : "鄧加和眾多足球巨星齊聚迪拜，為以太秀秀歐洲發佈會助力!",
        SECTION_NEWS_ITEM_TITLE_3            : "以太秀秀在曼谷與泰國王室聯合舉辦了一次發佈會",
        SECTION_NEWS_ITEM_TITLE_4            : "泰國王室成員、電影明星和來自世界各地的投資者都參加了在曼谷索菲特酒店舉辦的以太秀秀盛宴",
        SECTION_NEWS_ITEM_TITLE_5            : "韓國首爾以太秀秀發佈會",
        SECTION_FOLLOW_TITLE_1               : "Disclaimer",
        SECTION_FOLLOW_TITLE_2               : "",
        FOOTER_POLICY                        : "© CopyRight 2017-2018",
        FOOTER_TERMS                         : "隱私政策",
        FOOTER_AGGREMENT                     : "條款",
        FOOTER_FUNDATION                     : "ESS.TW Inc. All Rights Reserved.",
        IMG_PROBLEM                          : "./src/problem-en.png",
        IMG_SOLUTION                         : "./src/solution-en.png",
        IMG_INC_TOKEN_1                      : "./src/inc-token-1-en.png",
        IMG_INC_TOKEN_2                      : "./src/inc-token-2-en.png",
        DIALOG_LOGIN_TITLE                   : "登錄",
        DIALOG_LOGIN_EMAIL                   : "郵箱",
        DIALOG_LOGIN_PASSWORD                : "密碼",
        DIALOG_LOGIN_IMAGE_CAPTCHA           : "圖形驗證碼",
        DIALOG_LOGIN_BTN_LOGIN               : "登錄",
        DIALOG_LOGIN_REMEMBER                : "記住我",
        DIALOG_LOGIN_FORGET                  : "忘記密碼？",
        DIALOG_REGISTER_TITLE                : "註冊",
        DIALOG_REGISTER_EMAIL                : "郵箱",
        DIALOG_REGISTER_PASSWORD             : "密碼",
        DIALOG_REGISTER_IMAGE_CAPTCHA        : "圖形驗證碼",
        DIALOG_REGISTER_EMAIL_CAPTCHA        : "郵箱驗證碼",
        DIALOG_REGISTER_BTN_REGISTER         : "註冊",
        DIALOG_REGISTER_CAN_NOT_REGISTER     : "無法註冊？",
        DIALOG_REGISTER_REGISTER_HELPER_1    : "將您的郵箱、姓名、身份證號、身份證照片發送到",
        DIALOG_REGISTER_REGISTER_HELPER_2    : "。我們將在 2 個工作日內完成驗證，並將您的登錄信息發送到您的郵箱",
        DIALOG_FORGET_TITLE                  : "重置密碼",
        DIALOG_FORGET_EMAIL                  : "郵箱",
        DIALOG_FORGET_IMAGE_CAPTCHA          : "圖形驗證碼",
        DIALOG_FORGET_EMAIL_CAPTCHA          : "郵箱驗證碼",
        DIALOG_FORGET_PASSWORD               : "密碼",
        DIALOG_FORGET_BTN_RESET              : "重置",
        DIALOG_FORGET_BACK_TO_LOGIN          : "返回登錄",
        DIALOG_AUTHENTICATION_TITLE          : "身份認證",
        DIALOG_AUTHENTICATION_SUB_TITLE      : "提交申購錢請先進行身份認證",
        DIALOG_AUTHENTICATION_REALNAME       : "真實姓名",
        DIALOG_AUTHENTICATION_ID_NUMBER      : "證件號",
        DIALOG_AUTHENTICATION_UPLOAD         : "請上傳證件照片",
        DIALOG_AUTHENTICATION_UPLOAD_HINT    : "請上傳您的身份證或者護照的圖片",
        DIALOG_AUTHENTICATION_IMAGE_CAPTCHA  : "圖形驗證碼",
        DIALOG_AUTHENTICATION_BTN_DONW       : "完成",
        GET_CODE                             : "獲取驗證碼",
        BTN_PRESALE                          : "預售",
        BTN_ACCOUNT                          : "賬戶",
        SELECT_NATIONALITY_DEFAULT           : "- 選擇國家 -",
        ERROR_INVALID_EMAIL                  : "請正確填寫的郵箱地址",
        ERROR_INVALID_PASSWORD               : "請正確填寫密碼",
        ERROR_INVALID_CAPTCHA                : "請正確填寫驗證碼",
        ERROR_INVALID_IMAGE_CAPTCHA          : "請正確填寫圖形驗證碼",
        ERROR_INVALID_EMAIL_CAPTCHA          : "請正確填寫郵箱驗證碼",
        ERROR_EMPTY_REALNAME                 : "請輸入真實姓名",
        ERROR_EMPTY_ID_NUMBER                : "請輸入證件號",
        ERROR_EMPTY_COUNTRY                  : "請輸入國家",
        ERROR_EMPTY_ID_PHOTO                 : "請上傳證件照片",
        MESSAGE_EMAIL_SENT                   : "郵件已發送",
        MESSAGE_PASSWORD_RESET               : "密碼已重置，現在帶您去登錄",
        DICT_XMZC:"Project creation",
        DICT_CYJJ:"Industrial focus",
        DICT_CYJJ_DL_1:"It is known to all that this is a golden age of knowledge change. What the original people most want to see is that their work is red; and the most sad thing is that their work makes others red... Plagiarism, piracy, wanton reprint, and so on, in this era of everyone will turn the firewall, become so ordinary, so unscrupulous.",
        DICT_CYJJ_DL_2:"This situation not only causes losses to these originators, but also limits the initiative of the original, which has a great negative impact on the development of the whole knowledge and culture field.",
        DICT_CYJJ_BTN:"Market pain point",
        DICT_YYCJ:"Application scene",
        DICT_YYCJ_DL_01:"ESS has realized the collection, confirmation, encryption, certificate keeping, anti-theft version, exchange, distribution, evaluation, ranking, distribution, trading, reward, crowdsourcing, crowdsourcing, etc. of various intellectual property rights.",
        DICT_YYCJ_BTN:"Application scene",
        DICT_XMJS:"Project introduction",
        DICT_XMJS_DL_01:"Before launching the project, Mr. Ling Zhiping pointed out that the application of block chain technology in the field of intellectual property, especially for protecting original words, voice, pictures, images, patents, mail delivery, information transmission and other contents, will play an unprecedented positive role.",
        DICT_XMJS_DL_02:'"In accordance with this policy, the blockchain" Ethernet (English show name: Ether show, abbreviation: ESS) \", is to block chain technology as the underlying globalization, open ecosystem. The platform opens the original ecological code, and developers can build and publish new projects to enhance the application of block chain technology in more industries.',
        DICT_XMJS_DL_03:"ESS is an international technology leading block chain project based on Ethernet smart contract. It is a smart original traceability platform. ESS is composed of three layers, namely, the basic level, the architecture level and the application level.",
        DICT_XMJS_BTN1:"Project creation",
        DICT_XMJS_BTN2:"Solution",
        DICT_SP:"Video",
        DICT_SP_DES:"Speech by Mr. Ling zhiping",

        TEAM_01_TIT:"Technical team",

        TEAM_01_01_NAME:"區塊鏈總架構師 Alger",
        TEAM_01_01_DEC:"多年區塊鏈技術開發和實踐經驗",
        TEAM_01_01_DEC_02:"熟悉多代虛擬貨幣",
        TEAM_01_01_DEC_03:"熟悉區塊鏈產品底層代碼技術",

        TEAM_01_02_NAME:"Ben, the head of the technical tea",
        TEAM_01_02_DEC:"Senior PHP Engineer",
        TEAM_01_02_DEC_02:"Senior safety inspection engineer",
        TEAM_01_02_DEC_03:"Familiarity with the underlying application technology of block chain",
        TEAM_01_02_DEC_04:"Familiarity with the stock trading system",
        TEAM_01_02_DEC_05:"Familiarity with the rules of computer software in the financial field",

        TEAM_01_03_NAME:"Business architecture design Channing",
        TEAM_01_03_DEC:"Business architect",
        TEAM_01_03_DEC_02:"Financial lawyer",
        TEAM_01_03_DEC_03:"The top layer commercial architecture design in the Internet field",
        TEAM_01_03_DEC_04:"Financial legal services",

        TEAM_02_TIT:"Financial team",
        TEAM_02_NAME:"Wuyulong",
        TEAM_02_DEC:"Chief operating officer",
        TEAM_02_DEC_001:"TaipeiPWC Taiwan",
        TEAM_02_NAME_02:"",
        TEAM_02_DEC_02:"",

        TEAM_03_TIT:"Legal team",
        TEAM_03_NAME:"Legal team: Lin Hao Tang",
        TEAM_03_DEC:"Logon Court: Taipei local court",
        TEAM_03_DEC_2:"TaiwanLogon guild:",
        TEAM_03_DEC_3:"Taipei Lawyers",
        TEAM_03_DEC_4:"GuildKaohsiung Lawyers",
        TEAM_03_DEC_5:"GuildTaoyuan lawyer's Guild",
        TEAM_03_BTN:"legal instrument",

        TEAM_04_TIT:"顧問團隊",
        TEAM_04_01_NAME:"苏国历",
        TEAM_04_01_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_02_NAME:"鲁长军",
        TEAM_04_02_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_03_NAME:"贺铿",
        TEAM_04_03_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_04_NAME:"孙祺扬",
        TEAM_04_04_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_05_NAME:"邱鸿彬",
        TEAM_04_05_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",
        TEAM_04_06_NAME:"吴忌寒",
        TEAM_04_06_DEC:"南美共同体(官方)亚洲联合发展商会驻中国首席代表",

        DBYT_TIT:"Tokens to use",
        DBYT_DL_TIT:"Maintenance of the etheric Xiu Xiu block chain operation",
        DBYT_DL_DEC:"Go to the center of the accounting system as a distributed Ethernet show, need to be involved in accounting with blockchain Token incentive accounting node, to maintain the normal operation of the chain block.",
        DBYT_DL_TIT_02:"Commercial application transaction",
        DBYT_DL_DEC_02:"A variety of commercial applications of Ethernet show payment: a reward, rights issue transaction fees, agency fees, royalties, the congregation raised platform Crowdsourcing royalty, transaction fees, cash withdrawal fees etc..",
        DBYT_DL_TIT_03:"Token",
        DBYT_DL_DEC_03:"TokenTotal: 999999999 gold coins Ether show, never seo.",

        ESS_TITLE:"Ether show",
        ESS_TITLE_02:"Angel wheel participant",
        ESS_LIST_TYPE:"Angel wheel",
        ESS_LIST_STATUS:"Participate in complete",
        ESS_LIST_NAME_01:"Macao trade and Investment Promotion Association Executive Vice President Zeng Waugh",
        ESS_LIST_NAME_02:"Macao Tian Ying International Investment Company Chairman Lin Yuan",
        ESS_LIST_NAME_03:"Macao Jinma international investment director and general manager Zhang Jinghai",
        ESS_LIST_NAME_04:"Macao Li hair chemical development company general manager Lin Yi",

        STATEMENT:"The site is used only to convey information, and does not construct a cost specific case. The above information or analysis does not constitute an investment decision. This website does not constitute any investment proposal, investment intention or instigation of investment. This document is not composed or understood to provide any act of buying and selling securities, nor is it any form of contract or commitment. Related intentions, users clearly understand the risks of this project. Once investors participate in investment, they will understand and accept the risk of the project, and are willing to undertake all the corresponding results or consequences for them. The operation team does not bear any direct or indirect losses involved in this project."
    },
};
//# sourceMappingURL=dict.js.map
